bdrs_system/urls.py
from django.contrib import admin
from django.urls import path, include

from error.views import LevelErrorHandler
from checkselection.views import CheckselectionHandler
from resultmanagement.views import ResultManagementHandler

urlpatterns = [
    # path('admin/', admin.site.urls, name = 'admin'),
    # path('', LoginHandler),
    # path('login/', LoginHandler, name = 'login'),
    # path('changepsw/', ChangePassWord, name = 'changepsw'),
    # path('levelerror/', LevelErrorHandler, name = 'levelerror'),
    # path('home/', HomeHandler, name = 'home'),
    # path('selection/', SelectionHandler, name = 'selection'),
    # path('checkselection/', CheckselectionHandler, name = 'checkselection'),
    # path('resultmanagement/', ResultManagementHandler, name = 'resultmanagement'),
    path('', include('users.urls', namespace='users')),
    path('questionnaire/',include('questionnaire.urls',namespace='questionnaire')),
]

questionnaire/urls.py
from django.urls import path

from . import views

app_name="questionnaire"
urlpatterns = [
    path('',views.questionPage,name='questionPage'),
    path('experiment/',views.experiment,name='experiment'),
]

users/urls.py
from django.urls import path

from . import views

app_name="users"
urlpatterns = [
    path('',views.loginIndex,name='loginIndex'),
    path('login/',views.loginIndex,name='loginIndex'),
    path('index/',views.index,name='index'),
    path('userLogin/',views.userLogin,name='userLogin'),
    path('userLogout/',views.userLogout,name='userLogout'),
    path('userSettings/',views.userSettings,name='userSettings'),
]

questionnaire/models.py
from django.db import models

# Create your models here.

questionnaire/views.py
#-*-coding:utf-8-*-
from django.shortcuts import render
from django.http import HttpResponse
from users.views import level_auth
from bdrs_system.settings import REDIS_HOST, REDIS_PORT

import redis
# import logging
import json

@level_auth(0,1,2)
def questionPage(request):
    userid = request.session['userid']
    username = request.session['username']
    conn = redis.Redis(host=REDIS_HOST, port=REDIS_PORT, db=0)
    majorclass = conn.hget('student:' + str(userid), 'majorclass').decode('utf-8')
    # logging.debug(majorclass)
    booklist = conn.smembers('book:' + str(majorclass))
    # logging.debug(booklist)
    allinfo = []
    for inbook in booklist:
        book = {}
        book['ID'] = inbook.decode('utf-8')
        bookinfo = conn.hgetall('book:' + book['ID'])
        book['name'] = bookinfo[b'name'].decode('gbk', errors='ignore')
        book['price'] = bookinfo[b'price'].decode('utf-8')
        book['discount'] = bookinfo[b'discount'].decode('utf-8')
        allinfo.append(book)
    # logging.debug(allinfo)
    # jsondata = json.dumps(allinfo)
    # logging.debug(jsondata)
    return render(request, 'questionnaire/questionnaire.html', {'allinfo':allinfo, 'userid':userid, 'username':username, 'error':None})

def experiment(request):
    if request == "POST":
        print("返回的数据是")
        print(request.body)
    return HttpResponse(request.body)

questionnaire/templates/questionnaire/questionnaire.html
{% extends "users/base.html" %}
{% load static %}
{% block css %}<link rel="stylesheet" type="text/css" href="{% static 'questionnaire/css/questionnaire.css'%}">{% endblock css %}
{% block title %}选书统计{% endblock title %}
{% block content %}
  <div class="questionnaire">
    <div class="errors">
      {% if errors %}
        {% for error in errors %}
          <p style="color:red;">
            {{ error }}
          </p>
        {% endfor %}
      {% endif %}
    </div>
    <div class="dataZone">
      <p>书名</p>
      <p>价格</p>
      <p>折扣</p>
      <p>是否选中</p>
    </div>
    <form class="questionForm" action="{% url 'questionnaire:experiment' %}" method="POST">
      {% csrf_token %}
      <div class="questionDiv">
        <p class="questionId1">bookname1</p>
        <p class="questionData11">bookprice1</p>
        <p class="questionData12">bookdiscount1</p>
        <div class="icon">
          <i class="far fa-square"></i>
        </div>
        <input type="hidden" name="questionId1" value="0">
      </div>
      <div class="questionDiv">
        <p class="questionId2">bookname2</p>
        <p class="questionData21">bookprice2</p>
        <p class="questionData22">bookdiscount2</p>
        <div class="icon">
          <i class="far fa-square"></i>
        </div>
        <input type="hidden" name="questionId2" value="0">
      </div>
      <div class="questionDiv">
        <p class="questionId3">bookname3</p>
        <p class="questionData31">bookprice3</p>
        <p class="questionData32">bookdiscount3</p>
        <div class="icon">
          <i class="far fa-square"></i>
        </div>
        <input type="hidden" name="questionId3" value="0">
      </div>
      <p id="submitButton">提交</p>
    </form>
  </div>
{% endblock content %}
{% block js %}<script type="text/javascript" src="{% static 'questionnaire/scripts/questionnaire.js' %}"></script>{% endblock js %}