bdrs_system/urls.py
from django.contrib import admin
from django.urls import path, include

from error.views import LevelErrorHandler
from checkselection.views import CheckselectionHandler
from resultmanagement.views import ResultManagementHandler

urlpatterns = [
    # path('admin/', admin.site.urls, name = 'admin'),
    # path('', LoginHandler),
    # path('login/', LoginHandler, name = 'login'),
    # path('changepsw/', ChangePassWord, name = 'changepsw'),
    # path('levelerror/', LevelErrorHandler, name = 'levelerror'),
    # path('home/', HomeHandler, name = 'home'),
    # path('selection/', SelectionHandler, name = 'selection'),
    # path('checkselection/', CheckselectionHandler, name = 'checkselection'),
    # path('resultmanagement/', ResultManagementHandler, name = 'resultmanagement'),
    path('', include('users.urls', namespace='users')),
    path('questionnaire/',include('questionnaire.urls',namespace='questionnaire')),
]

questionnaire/urls.py
from django.urls import path

from . import views

app_name="questionnaire"
urlpatterns = [
    path('',views.questionPage,name='questionPage'),
    path('experiment/',views.experiment,name='experiment'),
]

users/urls.py
from django.urls import path

from . import views

app_name="users"
urlpatterns = [
    path('',views.loginIndex,name='loginIndex'),
    path('login/',views.loginIndex,name='loginIndex'),
    path('index/',views.index,name='index'),
    path('userLogin/',views.userLogin,name='userLogin'),
    path('userLogout/',views.userLogout,name='userLogout'),
    path('userSettings/',views.userSettings,name='userSettings'),
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
#-*-coding:utf-8-*-
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.views.generic.base import View
from django.shortcuts import render
from bdrs_system.settings import REDIS_HOST, REDIS_PORT

import redis
import logging
import chardet

def level_auth(*args):
    def echo(func):
        def wrapper(request, *arg, **kwargs):
            level = request.session.get('level')
            if not level:
                return HttpResponseRedirect('/login/')
            if int(level) in args:
                return func(request, *arg, **kwargs)
            return HttpResponseRedirect('/levelerror/')
        return wrapper
    return echo

def loginIndex(request):
    return render(request,'users/loginIndex.html')

def clear_session(request):
	request.session.clear()

@level_auth(0,1,2)
def index(request):
    return render(request,'users/index.html', {'userid':request.session['userid'], 'username':request.session['username']})

def userLogin(request):
    errors=[]
    account=None
    password=None
    if request.method=='POST':
        account=request.POST.get('account')
        password=request.POST.get('password')
        print(account)
        print(password)
        conn = redis.Redis(host=REDIS_HOST, port=REDIS_PORT, db=0)
        data = conn.hgetall('student:' + account)
        print(data)
        if data:
            if data[b'password'] == password.encode('utf-8'):
                request.session['userid'] = account
                request.session['username'] = data[b'username'].decode('gbk', errors='ignore')
                request.session['level'] = data[b'level'].decode('utf-8')
                # logging.debug(request.session['usrname'])
                # logging.debug(request.session['level'])
                # logging.debug("success") 
                user = {}
                user['is_authenticated'] = True
                user['info'] = account + ":" + request.session['username'] 
                return HttpResponseRedirect('/index')
            else:
                errors.append('用户名或密码错误')
        else:
            errors.append('用户名或密码错误')
        return render(request,'users/loginIndex.html',{'errors':errors})

    

@level_auth(0,1,2)
def userLogout(request):
    clear_session(request)
    return HttpResponseRedirect('/')

@level_auth(0,1,2)
def userSettings(request):
    return render(request,'users/settings.html', {'userid':request.session['userid'], 'username':request.session['username']})












# @level_auth(0,1,2)
# def ChangePassWord(request):
#     if request.method == 'POST':
#         return ChangePassWordPost(request)
#     else:
#         return ChangePassWordGet(request)

# def ChangePassWordGet(request):
#     form = ChangePSWForm()
#     return render(request,'changepsw.html', {'form': form, 'error':None})

# def ChangePassWordPost(request):
#     form = ChangePSWForm(request.POST)
#     if form.is_valid():
#         userid = request.session['userid']
#         oldpassword = form.cleaned_data['oldpassword']
#         newpassword = form.cleaned_data['newpassword']
#         newpasswordagain = form.cleaned_data['newpasswordagain']
#         if newpassword == newpasswordagain:
#             conn = redis.Redis(host='127.0.0.1', port=6379, db=0)
#             nowpsd = conn.hget('student:' + str(userid), b'password')
#             if nowpsd == oldpassword.encode('utf-8'):
#                 conn.hset('student:' + str(userid), b'password', newpassword)
#                 return render(request,'changepsw.html', {'form':form, 'message':'密码修改成功'})
#             else:
#                 return render(request,'changepsw.html', {'form':form, 'error':'旧密码输入错误'})     
#         else:
#             return render(request,'changepsw.html', {'form':form, 'error':'两次输入的新密码不一致'})
#     else:
#         return render(request,'changepsw.html', {'form':form, 'error':'无效的提交数据'})

users/templates/users/base.html
<!DOCTYPE html>
<html>
  <head>
    {% load static %}
    <meta charset="utf-8"/>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'users/css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'users/css/all.min.css' %}">
    {% block css %}{% endblock css %}
    <script type="text/javascript">document.documentElement.style.fontSize=(window.screen.width/1536*625)+"%";document.documentElement.style.visibility="hidden";document.onreadystatechange=function(){if(document.readyState=="complete"){document.documentElement.style.visibility="visible";}}</script>
  </head> 
<body>
  <div class="header">
    <img class="headerLogo" title="logo" src="{% static 'users/images/个人.png' %}" />
    {% if user.is_authenticated %}
      <a class="headerTitle" href="{% url 'users:index' %}">我的猫不可能这么可爱</a>
    {% else %}
      <a class="headerTitle" href="{% url 'users:loginIndex' %}">我的猫不可能这么可爱</a>
    {% endif %}
    <div class="headerRight">
      {% if userid %}
        <span>Hi,</span>
        <div class="menu">
          <span class="baseUsername">{{ userid }} : {{ username }}</span>
            <ul class="menuContent">
              <li>
                <a href="{% url 'users:userSettings' %}">信息</a>
              </li>
              <li>
                <a href="{% url 'users:userLogout' %}">注销</a>
              </li>
            </ul>
        </div>
        <span>!</span>
      {% else %}
        <span class="loginNow">Login Now</span>
      {% endif %}
    </div>
  </div>
  <div class="placeholder"></div>
  {% block content %}{% endblock content %}
  <script type="text/javascript" src="{% static 'users/scripts/base.js' %}"></script>
  {% block js %}{% endblock js %}
</body>

users/templates/users/index.html
{% extends "users/base.html" %}
{% load static %}
{% block title %}首页{% endblock title %}
{% block css %}<link rel="stylesheet" type="text/css" href="{% static 'users/css/index.css'%}">{% endblock css %}
{% block content %}
<div class="container"></div>
<div class="background"></div>
<div class="hello">
  <div class="hellozone">
    <p class="p1">Hi!</p>
    <p class="p2">我的猫不可能这么可爱</p>
  </div>
  <p class="p3">ฅ՞•ﻌ•՞ฅ</p>
</div>
<div class="contentDiv">
  <div class="contentTop">
    <ul>
      <li class="li1 CTclick">快速导航</li>
      <li class="li2">关于本站</li>
    </ul>
    <div class="logos">
      <i class="fab fa-qq"><div><img src="{% static 'users/images/二维码.jpg' %}"/></div></i>
      <i class="fab fa-weixin"><div><img src="{% static 'users/images/二维码.jpg' %}"/></div></i>
      <i class="fab fa-weibo"><div><img src="{% static 'users/images/二维码.jpg' %}"/></div></i>
      <i class="fab fa-github"><div><img src="{% static 'users/images/二维码.jpg' %}"/></div></i>
    </div>
  </div>
  <div class="content">
    <div class="content1 CTV">
      <ul>
        <li class="ctl1">
          <div class="leftLogos">
            <ul>
              <li class="lL1">
                <a href="#">
                  <img src="{% static 'users/images/社交.png' %}" />
                  <span>猫の论坛</span>
                </a>
              </li>
              <li class="lL2">
                <a href="#">
                  <img src="{% static 'users/images/医疗.png' %}" />
                  <span>猫の医院</span>
                </a>
              </li>
              <li class="lL3">
                <a href="#">
                  <img src="{% static 'users/images/购物车.png' %}" />
                  <span>猫の商店</span>
                </a>
              </li>
              <li class="lL4">
                <a href="#">
                  <img src="{% static 'users/images/档案.png' %}" />
                  <span>猫の寄养</span>
                </a>
              </li>
            </ul>
          </div>
          <div class="news">
            <p>喵站大小事</p><span><img src="{% static 'users/images/新闻.png' %}"/></span>
            <ul>
             <li><a href="{% url 'questionnaire:questionPage' %}">投票这是第一个链接投票这是第一个链接投票这是第一个链接投票这是第一个链接投票这是第一个链接投票这是第一个链接</a></li>
             <li><a href="#">这是第二条链接</a></li>
             <li><a href="#">这是第三条链接</a></li>
             <li><a href="#">这是第四条链接</a></li>
             <li><a href="#">这是第五条链接</a></li>
             <li><a href="#">这是第六条链接</a></li>
             <li><a href="#">这是第七条链接</a></li>
             <li><a href="#">这是第八条链接</a></li>
            </ul>
          </div>
        </li>
        <li class="ctl2">
          <div class="imgZone">
          </div>
          <div class="textZone">
            <h2>猫の论坛</h2>
            <p>XXXXXXXXXXXXXXXXXXX的论坛</p>
            <div class="hiddenDiv"><a href="#"><i class="fas fa-angle-double-right"></i><p>进入板块</p></a></div>
          </div>
        </li>
        <li class="ctl3">
          <div class="imgZone">
          </div>
          <div class="textZone">
            <h2>猫の医院</h2>
            <p>XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX这里可以XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX这里可以XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX</p>
            <div class="hiddenDiv"><a href="#"><i class="fas fa-angle-double-right"></i><p>进入板块</p></a></div>
          </div>
        </li>
        <li class="ctl4">
          <div class="imgZone">
          </div>
          <div class="textZone">
            <h2>猫の商店</h2>
            <p>XXXXXXXXXXXXXXXXXXXXXXXXXXXXX</p>
            <div class="hiddenDiv"><a href="#"><i class="fas fa-angle-double-right"></i><p>进入板块</p></a></div>
          </div>
        </li>
        <li class="ctl5">
          <div class="imgZone">
          </div>
          <div class="textZone">
            <h2>猫の寄养</h2>
            <p>XXXXXXXXXXXXXXXXXXXXXXXXXXXXX</p>
            <div class="hiddenDiv"><a href="#"><i class="fas fa-angle-double-right"></i><p>进入板块</p></a></div>
          </div>
        </li>
      </ul>
    </div>
    <div class="content2">
      <div class="webTips">
        <p>    我从小就喜欢猫，一直想要猫，但是因为各种原因始终没有猫，这么多年我都跟自己说，会有猫的。现在口口声声说喜欢猫的人太多，也有许多人买了猫，但是有部分人确实是一时兴起，完全没有必要的知识，反倒害了喵主子。有人觉得绝育是很过分很残忍；有人甚至觉得猫粮喂全素的最好。开玩笑啊，猫要肉和鱼啊！挺多猫因为仆人们喂素食，健康堪忧啊。因此，真的最好有一个平台，能够整合相关知识，比如猫粮怎么搭。后期还可以接入寄养啊急救啊买优选粮等等服务，这一举颠覆了在群里问怎么养猫的不靠谱行为，对猫主子负责，也是对仆人们负责。我从小就喜欢猫，一直想要猫，但是因为各种原因始终没有猫，这么多年我都跟自己说，会有猫的。现在口口声声说喜欢猫的人太多，也有许多人买了猫，但是有部分人确实是一时兴起，完全没有必要的知识，反倒害了喵主子。有人觉得绝育是很过分很残忍；有人甚至觉得猫粮喂全素的最好。开玩笑啊，猫要肉和鱼啊！挺多猫因为仆人们喂素食，健康堪忧啊。因此，真的最好有一个平台，能够整合相关知识，比如猫粮怎么搭。后期还可以接入寄养啊急救啊买优选粮等等服务，这一举颠覆了在群里问怎么养猫的不靠谱行为，对猫主子负责，也是对仆人们负责。我从小就喜欢猫，一直想要猫，但是因为各种原因始终没有猫，这么多年我都跟自己说，会有猫的。现在口口声声说喜欢猫的人太多，也有许多人买了猫，但是有部分人确实是一时兴起，完全没有必要的知识，反倒害了喵主子。有人觉得绝育是很过分很残忍；有人甚至觉得猫粮喂全素的最好。开玩笑啊，猫要肉和鱼啊！挺多猫因为仆人们喂素食，健康堪忧啊。因此，真的最好有一个平台，能够整合相关知识，比如猫粮怎么搭。后期还可以接入寄养啊急救啊买优选粮等等服务，这一举颠覆了在群里问怎么养猫的不靠谱行为，对猫主子负责，也是对仆人们负责。我从小就喜欢猫，一直想要猫，但是因为各种原因始终没有猫，这么多年我都跟自己说，会有猫的。现在口口声声说喜欢猫的人太多，也有许多人买了猫，但是有部分人确实是一时兴起，完全没有必要的知识，反倒害了喵主子。有人觉得绝育是很过分很残忍；有人甚至觉得猫粮喂全素的最好。开玩笑啊，猫要肉和鱼啊！挺多猫因为仆人们喂素食，健康堪忧啊。因此，真的最好有一个平台，能够整合相关知识，比如猫粮怎么搭。后期还可以接入寄养啊急救啊买优选粮等等服务，这一举颠覆了在群里问怎么养猫的不靠谱行为，对猫主子负责，也是对仆人们负责。</p>
      </div>
    </div>
  </div>
</div>
{% endblock content %}
{% block js %}
<script type="text/javascript" src="{% static 'users/scripts/index.js' %}"></script>
{% endblock js %}

users/templates/users/loginIndex.html
{% extends "users/base.html" %}
{% load static %}
{% block title %}登陆{% endblock title %}
{% block css %}<link rel="stylesheet" type="text/css" href="{% static 'users/css/loginIndex.css'%}">
{% endblock css %}\
{% block content %}
  <div class="loginIndexContent">
    <div class="slide">
      <ul class="pictures">
        <li class="picture1"></li>
        <li class="picture2"></li>
        <li class="picture3"></li>
        <li class="picture4"></li>
        <li class="picture5"></li>
      </ul>
      <ul class="circles">
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
      </ul>
    </div>
    <div class="rightContent">
      <img class="loginImg" src="{% static 'users/images/猫.png' %}" />
      <form action="{% url 'users:userLogin' %}" class="loginForm" method="POST">
        <div class="errors">
          {% if errors %}
            {% for error in errors %}
              <p>{{ error }}</p>
            {% endfor %}
          {% endif %}
        </div>
        {% csrf_token %}
  		  <p class="pusername">Username</p>
        <input class="username" type="text" name="account" value='' required autocomplete="on" />
        <p class="error1">请输入账号</p>
        <p class="ppassword">Password</p>
  	   	<input class="password" type="password" name="password" value='' required autocomplete="on" />
        <p class="error2">请输入密码</p>
  	    <div class="logos">
  		  <a href="#"><img src="{% static 'users/images/icon_github.png' %}" /></a>
  		  <a href="#"><img src="{% static 'users/images/QQ.png' %}" /></a>
  		  <a href="#"><img src="{% static 'users/images/微博.png' %}" /></a>
            <a href="#">
  		  <img src="{% static 'users/images/微信.png' %}" /></a>
  	    </div>
  	    <a href="#" class="login">Log In</a>
  	  </form>
    </div>
  </div>
{% endblock content %}
{% block js %}
<script type="text/javascript" src="{% static 'users/scripts/loginIndex.js' %}"></script>
{% endblock js %}

users/templates/users/register.html
{% extends "users/base.html" %}
{% load static %}
{% block content %}
  <div class="errors">
    {% if errors %}
      {% for error in errors %}
        <p style="color:red;">
          {{ error }}
        </p>
      {% endfor %}
    {% endif %}
  </div>
  <form action="{% url 'users:userRegister' %}" class="registerForm" method="POST"> 
    {% csrf_token %}
    <span>账号:</span>
    <input class="username" type="text" name="account" required>
    <span>昵称:</span>
    <input class="name" type="text" name="name" required>
    <span>第一次密码:</span>
    <input class="password" type="password" name="password" required>
    <span>第二次密码:</span>
    <input class="password2" type="password" name="password2" required>
    <span>邮箱:</span>
    <input class="email" type="text" name="email" required>
    <input class="submit" type="submit" name="submit" value="提交">
  </form>
  <script type="text/javascript" src="{% static 'users/scripts/register.js' %}"></script>
{% endblock content %}

users/templates/users/settings.html
{% extends "users/base.html" %}
{% load static %}
{% block title %}个人信息设置{% endblock title %}
{% block css %}<link rel="stylesheet" type="text/css" href="{% static 'users/css/settings.css'%}">{% endblock css %}
{% block content %}
  <div class="settings">
    <div class="settingsContent">
      <div class="permissions">
        <p>查询班级(仅管理员可见)</p>
        <ul>
          <li><p>一班</p></li>
          <li><p>二班</p></li>
          <li><p>三班</p></li>
        </ul>
      </div>
      <div class="changePassword" style="display:none;">
        <p id="changePasswordTitle">修改密码</p>
        <form method="POST" action="#" class="settingsForm">
          {% csrf_token %}
          <p>请输入原密码:</p>
          <input type="password" class="password" name="oldPassword1">
          <p>请再次输入原密码:</p>
          <input type="password" class="password" name="oldPassword2">
          <p>输入新密码:</p>
          <input type="password" class="password" name="newPassword">
          <p id="submitButton">提交</p>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}
{% block js %}

{% endblock js %}